import React, { Component } from 'react';
import MenuBar from './Home/MenuBar.js'
import './Waiver.css';


export default class Waiver extends Component {

	render() {
		return (
			<div className="bg1">
				<MenuBar/>
				<div className="container">
					<h1 className="title">TERMS OF AGREEMENT</h1>
					<p>This Agreement is entered upon the date of signing by and between the service provider and the user following the Terms used - hereinafter called ("Terms") on the basis of which you ("You") the User of the service can use the Autism Job Match  hereinafter called (“AJM”) as the free services provided by Autism Society Inland Empire. hereinafter called (“ASIE”) as follows: </p>
					<p>The Terms will constitute a binding agreement between the user - You and Autism Society Inland Empire. for using its Autism Job Match – ASIE operating through the Web site and are irrevocably accepted by You each time that You use or access the ASIE Sites and/or its Services. If You do not happen to accept the Terms stated herein, please do not use ASIE sites and the AJM’s Services. </p>
					<b>Understanding the rights and responsibilities stated herein under the provision of this agreement:</b>
					<br/><br/>
					<b>1. User's Criteria</b>
					<hr/>
					<p>Users must be 18 years of age or older to visit or use ASIE’s Sites particularly to use the Autism Job Match in any manner. If under the age of 18 or the age of majority specially on Autism Spectrum as that is defined, should use ASIE/AJM Job Sites under the supervision of a parent, legal guardian, or other responsible adult.</p>
					<b>2. Violation</b>
					<hr/>
					<p>Users who violate these Terms may have their access and use of the AJM Sites suspended or terminated, entirely at ASIE’s discretion if not remedied immediately to the satisfaction of ASIE.</p>
					<b>3. Privacy</b>
					<hr/>
					<p>ASIE’s website will provide all relevant questionnaire to be filled in while using this Job Match Portal allowing Users to create individual profiles, which may include personal information (”Profiles”), and to make these Profiles, or also to provide access to the prospective employers.  The ASIE’s Services through AJM Portal are defined as the applications and services offered by ASIE, including job match services for employment opportunities. ASIE reserves the right to revise these Terms at any time by posting an updated version to ASIE’s Web page. Users are advised to keep visiting this page periodically to review the most current Terms revised time to time depending upon the current situation, because they are binding on them.</p>
					<b>4. Agreement to Share Information</b>
					<hr/>
					<p>ASIE reserves the right to collaborate with Regional Center, Department of Rehabilitation, Workforce Development Board, other governmental or non-profit organizations with the expressed purposed of obtaining employment for individuals with Autism who are using the AJM.  Completion of this document authorizes the disclosure and/or use of individually identifiable information, as set forth below, consistent with California and Federal law concerning the privacy of such information.  You understand that you have to revoke this authorization at any time. The revocation must be in writing, signed by me or on my behalf, and delivered to the Autism Society Inland Empire, 420 N McKinley Suite 111-118, Corona, CA 92879.  Revocation will be effective upon receipt, but will not be effective to the extent that ASIE or others have acted in reliance upon this Authorization.</p>
					<b>5. Use of ASIE Services</b>
					<hr/>
					<p>The job posting, resume database (“ASIE’s Resume Database and the Autism Job Matching Services”) and other features of the ASIE AJM Sites may be used only by individuals seeking employment and/or career information and by employers seeking employees. Your use of the ASIE Services is also subject to any other contracts You may have with ASIE. In the case of any conflict between these Terms and any contract You have with ASIE, the terms of your contract will prevail. The term “job posting” as used herein shall mean information that You submit, publish or display on a ASIE Site or on its job portal – AJM, or social media that may be used to help promote these job postings.</p>
					<b>6. Confidentiality</b>
					<hr/>
					<p>You are responsible for maintaining the confidentiality of your Account, Profile and Passwords, as applicable. You should not share your password or other account access information with any other party, temporarily or permanently, and You shall be responsible for all uses of your ASIE’s Site registrations and passwords, whether or not authorized by You. You agree to immediately notify ASIE of any unauthorized use of your Account, Profile, or Passwords.</p>
					<b>7. All ASIE/AJM Users - agree not to:</b>
					<hr/>
					<p>(a) transmit, post, distribute, store or destroy material, including without limitation ASIE Content, in violation of any applicable law or regulation, including but not limited to laws or regulations governing the collection, processing, or transfer of personal information, or in breach of ASIE’s privacy policy; </p>
					<p>(b) take any action that imposes an unreasonable or disproportionately large load on any ASIE Site`s infrastructure; </p>
					<p>(c) use any device to navigate or search any ASIE Site other than the tools available on the Site, generally available third party web browsers, or other tools approved by ASIE; </p>
					<p>(d) use any data mining, robots or similar data gathering or extraction methods; </p>
					<p>(e) violate or attempt to violate the security of any ASIE Site including attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; </p>
					<p>(f) forge any OTHER packet header or any part of the header information in any e-mail or newsgroup posting; </p>
					<p>(g) reverse engineer or decompile any parts of any ASIE Site; </p>
					<p>(h) aggregate, copy or duplicate in any manner any of the ASIE Content or information available from any ASIE Site, including expired job postings, other than as permitted by these Terms; </p>
					<p>(i) frame or link to any ASIE Content or information available from any ASIE Site, unless permitted by these Terms; </p>
					<p>(j) post any content or material that promotes or endorses false or misleading information or illegal activities, or endorses or provides instructional information about illegal activities or other activities prohibited by these Terms, such as making or buying illegal weapons, violating someone`s privacy, providing or creating computer viruses or pirating media; </p>
					<p>(k) post any resume or Profile or apply for any job on behalf of another party; </p>
					<p>(l) share with a third party any login credentials to any ASIE Site; </p>
					<p>(m) access data not intended for You or logging into a server or account which You are not authorized to access; </p>
					<p>(m) post or submit to ASIE/AJM Site any incomplete, false or inaccurate biographical information or information which is not yours own; </p>
					<p>(o) post content that contains restricted or password-only access pages, or hidden pages or images; </p>
					<p>(p) solicit passwords or personally identifiable information from other Users; </p>
					<p>(q) delete or alter any material posted by any other person or entity; </p>
					<p>(r) harass, incite harassment or advocate harassment of any group, company, or individual; </p>
					<p>(s) send unsolicited mail or email, make unsolicited phone calls or send unsolicited faxes promoting and/or advertising products or services to any User, or contact any users that have specifically requested not to be contacted by You the User; </p>
					<p>(t) attempt to interfere with service to any User, host or network, including, without limitation, via means of submitting a virus to any ASIE Site, overloading, "flooding", "spamming", "mail bombing" or "crashing"; </p>
					<p>(u) promote or endorse an illegal or unauthorized copy of another person`s copyrighted work, such by as providing or making available pirated computer programs or links to them, providing or making available information to circumvent manufacture-installed copy-protect devices, or providing or making available pirated music or other media or links to pirated music or other media files; or </p>
					<p>(v) use the ASIE Services for any unlawful purpose or any illegal activity, or post or submit any content, resume, or job posting that is defamatory, libelous, implicitly or explicitly offensive, vulgar, obscene, threatening, abusive, hateful, racist, discriminatory, of a menacing character or likely to cause annoyance, inconvenience, embarrassment, anxiety or could cause harassment to any person or include any links to pornographic, indecent or sexually explicit material of any kind, as determined by ASIE’s discretion. </p>
					<p>NOTE: Violations of system or network security may result in civil and/or criminal liability. ASIE will investigate occurrences which may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting Users who are involved in such violations.</p>
					<b>8. Terms applicable to Registration by the Job Seekers.</b>
					<hr/>
					<p>When You register with any ASIE Site, You will be asked to create an account and provide ASIE with certain information including, without limitation, a valid email address (Your "Information"). </p>
					<p>Any Profile You submit must be accurate and describe You, an individual person. </p>
					<p>You acknowledge and agree that You are solely responsible for the form, content and accuracy of any resume or material contained therein placed by You on the ASIE/AJM Sites. </p>
					<p>You understand and acknowledge that You have no ownership rights in Your account and that if You cancel Your ASIE account or Your ASIE account is terminated, all Your account information from ASIE, including resumes, Profiles, cover letters, saved jobs, questionnaires will be marked as deleted in and may be deleted from ASIE`s databases and will be removed from any public area of the ASIE Sites. Information may continue to be available for some period of time because of delays in such deletion through ASIE’s web servers. However, ASIE reserves the right to delete Your account and all of Your Information after a significant duration of inactivity. Nevertheless, third parties may retain saved copies of Your Information beyond ASIE’s control. </p>
					<b>9. User Contents and Submissions.</b>
					<hr/>
					<p>You understand that all information, data, text, software, music, sound, photographs, graphics, video, advertisements, messages or other materials submitted, posted or displayed by You on or through a ASIE Site ("User Content") is the sole responsibility of the person from which such User Content originated. ASIE claims no ownership or control over any User Content. You or a third-party licensor, as appropriate, retain all patent, trademark and copyright to any User Content You submit, post or display on or through ASIE Portals and You are responsible for protecting those rights, as appropriate. By submitting, posting or displaying User Content on or through ASIE, You grant ASIE a worldwide, non-exclusive, royalty-free, transferable, sub-licensable license to use, reproduce, adapt, distribute and publish such User Content through ASIE. By submitting, posting or displaying User Content which is intended to be available to the general public, You grant ASIE a worldwide, non-exclusive, royalty-free license to reproduce, adapt, distribute and publish such User Content for the purpose of promoting ASIE and its services. ASIE will discontinue this licensed use within a commercially reasonable period after such User Content is removed from ASIE. ASIE reserves the right to refuse to accept, post, display or transmit any User Content in its sole discretion. </p>
					<p>You also represent and warrant that You have the right to grant, or that the holder of any rights, including moral rights in such content has completely and effectively waived all such rights and validly and irrevocably granted to You the right to grant, the license stated above. ASIE may review and remove any User Content that, in its sole judgment, violates these Terms, violates applicable laws, rules or regulations, is abusive, disruptive, offensive or illegal, or violates the rights of, or harms or threatens the safety of, Users of any ASIE Site. Thus ASIE reserves the right to expel Users and prevent their further access to the ASIE Sites and/or use of ASIE Services for violating the Terms or applicable laws, rules or regulations. ASIE may take any action with respect to User Content that it deems necessary or appropriate in its sole discretion if it believes that such User Content could create liability for ASIE, damage ASIE’s brand or public image, or cause ASIE to lose Users or (in whole or in part) its services or services of its other subsidiaries or Portals etc. </p>
					<p>ASIE does not represent or guarantee the truthfulness, accuracy, or reliability of User Content, derivative works from User Content, or any other communications posted by Users nor does ASIE endorse any opinions expressed by Users. You acknowledge that any reliance on material posted by other Users will be at Your own risk. </p>
					<b>The following is a list of User Content but not limited to, that are prohibited on the Application:  </b>
					<br/>
					<ul>
						<li>is implicitly or explicitly offensive, such as User Content that engages in, endorses or promotes racism, bigotry, discrimination, hatred or physical harm of any kind against any group or individual;</li>
						<li>harasses, incites harassment or advocates harassment of any group or individual;</li>
						<li>involves the transmission of “junk mail”, “chain letters,” or unsolicited mass mailing, “spamming” or “phishing”;</li>
						<li>promotes or endorses false or misleading information or illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;</li>
						<li>promotes or endorses an illegal or unauthorized copy of another person`s copyrighted work, such as providing or making available pirated computer programs or links to them, providing or making available information to circumvent manufacture-installed copy-protect devices, or providing or making available pirated music or other media or links to pirated music or other media files;</li>
						<li>contains restricted or password only access pages, or hidden pages or images;</li>
						<li>displays or links to pornographic, indecent or sexually explicit material of any kind;</li>
						<li>provides or links to material that exploits people under the age of 18 in a sexual, violent or other manner, or solicits personal information from anyone under 18; or</li>
						<li>provides instructional information about illegal activities or other activities prohibited by these Terms, including without limitation, making or buying illegal weapons, violating someone`s privacy, providing or creating computer viruses or pirating any media; and</li>
						<li>solicits passwords or personal identifying information from other Users.</li>
					</ul>
					<p>Any Profile You submit must describe You, an individual person. Examples of inappropriate and prohibited Profiles include, but are not limited to, Profiles that purport to represent an animal, place, inanimate object, fictional character, or real individual that is not You. </p>
					<p>We appreciate hearing from our Users and welcome Your comments regarding our services and the ASIE Sites. Please be advised, however, that our policy does not permit us to accept or consider creative ideas, suggestions, inventions or materials other than those which we have specifically requested. While we do value Your feedback on our services, please be specific in Your comments regarding our services and do not submit creative ideas, inventions, suggestions, or materials. If, despite our request, You send us creative suggestions, ideas, drawings, concepts, inventions, or other information (collectively the "Submission"), the Submission shall be the property of ASIE. None of the Submission shall be subject to any obligation of confidentiality on our part and we shall not be liable for any use or disclosure of any Submission. ASIE shall own exclusively all now known or later discovered rights to the Submission and shall be entitled to unrestricted use of the Submission for any purpose whatsoever, commercial or otherwise, without compensation to You or to any other person. </p>
					<b><u>Above all, the Users will be solely responsible for their own generated contents or any other contents which ASIE/AJM do not endorse, that they load and use on ASIE’s Portal. Users are directly liable to ensure that there is no infringement to other’s copyrights, trade-marks or intellectual properties etc. failing which Users irrevocably agree to indemnify ASIE/AJM and will solely be liable to any legal action against those contents, attorneys and legal/court fees in addition to all the cost incurred in addressing the complaints, legal summons or court orders etc.</u></b>
					<br/><br/><br/>
					<b>10. Notification Of Claimed Copyright or Trademark Infringement:</b>
					<hr/>
					<p>If You believe that Your copyrighted work or trademark has been uploaded, posted or copied to any ASIE Site and is accessible on such ASIE Site in a way that constitutes copyright or trademark infringement, please contact ASIE by email at info@ieautism.org or by regular mail at: </p>
					<b><i>Autism Society Inland Empire., 420 N McKinley Suite 111-118, Corona CA 92879</i></b>
					<br/><br/><br/>
					<b>11. Term and Termination Of Users Who Infringe The Copyright Or Other Intellectual Property Rights Of Others:</b>
					<hr/>
					<p>The Terms will remain in full force and effect while You are a User of any ASIE Site. </p>
					<p>ASIE reserves the right in case of breach of the Terms by You the User, at its sole discretion, either to pursue all of its legal remedies, including but not limited to removal of Your User Content from the ASIE/AJM Sites or immediately terminate Your registration with or ability to access the ASIE Sites and/or any other services provided to You by ASIE or if ASIE is unable to verify or authenticate any information You submit to a ASIE Site registration. Even after You are no longer a User of the ASIE Sites, certain provisions of these Terms will remain in effect.</p>
					<p>ASIE respects the intellectual property of others, and we ask our Users and content partners to do the same. The unauthorized posting, reproduction, copying, distribution, modification, public display or public performance of copyrighted works constitutes infringement of the copyright owners rights. As a condition to Your use of the ASIE Sites, You agree not to use any ASIE Site to infringe the intellectual property rights of others in any way. </p>
					<p>ASIE reserves the right to terminate the accounts of any Users, and block access to the ASIE Sites of any Users who are repeat infringers of the copyrights, or other intellectual property rights, of others. </p>
					<p>ASIE reserves the right, in its sole discretion, to take these actions to limit access to the Site and/or terminate the accounts of any time, in our sole discretion Users who infringe any intellectual property rights of others, whether or not there is any repeat infringement, with or without notice, and without any liability to the User who is terminated or to the User whose access is blocked. Notwithstanding with the above, in the event that You believe in good faith that a notice of copyright infringement has been wrongly filed against You, please contact ASIE as set forth in Section 10 above.</p>
					<b>12. ASIE`s Liability:</b>
					<hr/>
					<p>The ASIE/AJM Sites act as, among other things, venues for (i) employers to post job opportunities and search for and evaluate candidates for the Job, (ii) candidates to post resumes and (iii) work with government and non-government agencies to provide job matching services to increase the number of job interviews and employment for adults with Autism in the Inland Empire.   </p>
					<p>This is a pilot program.  ASIE makes no guarantee of services or employment by using AJM.  ASIE does not screen or censor the listings, including Profiles offered. ASIE is not involved in, and does not control, the actual transaction between employers and candidates. As a result, ASIE is not responsible for User Content, the quality, safety or legality of the jobs or resumes posted, the truth or accuracy of the listings, the ability of employers to offer job opportunities to candidates or the ability of candidates to fill job openings and ASIE makes no representations about any jobs, resumes or User Content on the ASIE Sites. While ASIE reserves the right in its sole discretion to remove User Content, job postings, resumes or other material from the its Sites from time to time, it also does not assume any obligation to do so and to the extent permitted by law, disclaims any liability for failing to take any such action.</p>
					<p>Note that there are risks, including but not limited to the risk of physical harm, of dealing with strangers, underage persons or people acting under false pretenses. You assume all risks associated with dealing with other users with whom You come in contact through the ASIE Sites. By its very nature other people’s information may be offensive, harmful or inaccurate, and in some cases will be mislabeled or deceptively labeled. We expect that You will use caution and common sense when using the ASIE Sites. </p>
					<p>Because User authentication on the Internet is difficult, ASIE cannot and does not confirm that each User is who they claim to be. Because we do not and cannot be involved in User-to-User dealings or control the behavior of participants on any ASIE Site, in the event that You have a dispute with one or more Users, You release ASIE(and our agents and employees) from claims, demands and damages (actual and consequential and direct and indirect) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes to the fullest extent permitted by law. </p>
					<p>The ASIE Sites and the Contents may contain inaccuracies or typographical errors. Thus ASIE makes no representations or claims about the accuracy, reliability, completeness, or timeliness of any ASIE Site or the ASIE Content. The use of all ASIE Sites and the ASIE Content are at Your own risk. Changes are periodically made to ASIE Sites and may be made at any time. ASIE cannot guarantee and does not promise any specific results from use of any ASIE Site. No advice or information, whether oral or written, obtained by a User from ASIE or through or from any ASIE Site shall create any warranty not expressly stated herein. </p>
					<p>If You are a California resident, You waive California Civil Code Section 1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor." </p>
					<p>ASIE encourages You to keep a back-up copy of any of Your User Content. To the extent permitted by law, in no event shall ASIE be liable for the deletion, loss, or unauthorized modification of any User Content. </p>
					<p>If You believe that something on the Site violates these Terms please contact our designated agent set forth in Section 10 above. </p>
					<p>If notified of any content or other materials which allegedly do not conform to these Terms, ASIE may in its sole discretion investigate the allegation and determine whether to remove or request the removal of the content. ASIE has no liability or responsibility to Users for performance or nonperformance of such activities.</p>
					<b>13. Limitation of Liability:</b>
					<hr/>
					<p>TO THE FULLEST EXTENT POSSIBLE BY LAW, ASIE`S MAXIMUM LIABILITY ARISING OUT OF OR IN CONNECTION WITH ANY ASIE SITE OR YOUR USE OF THE ASIE CONTENT, REGARDLESS OF THE CAUSE OF ACTION (WHETHER IN CONTRACT, TORT, BREACH OF WARRANTY OR OTHERWISE), WILL NOT EXCEED $50.</p>
					<b>14. Disclaimer of Warranty:</b>
					<hr/>
					<p>TO THE FULLEST EXTENT POSSIBLE BY LAW, ASIE DOES NOT WARRANT THAT ANY ASIE SITE/PORTAL OR ANY ASIE SERVICES WILL OPERATE ERROR-FREE OR THAT ANY ASIE SITE AND ITS SERVERS ARE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL MECHANISMS. IF YOUR USE OF ANY ASIE/AJM SITE OR THE CONTENT RESULTS IN THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA OR ANY OTHER COSTS, ASIE IS NOT RESPONSIBLE FOR THOSE COSTS. THE ASIE SITES AND ITS CONTENT ARE PROVIDED ON AN "AS IS" BASIS WITHOUT ANY WARRANTIES OF ANY KIND. ASIE, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTY OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE AND NON-INFRINGEMENT. ASIE MAKES NO WARRANTIES ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE ASIE CONTENT, SERVICES, SOFTWARE, TEXT, GRAPHICS, AND LINKS.</p>
					<b>15. Disclaimer of Consequential Damages:</b>
					<hr/>
					<p>TO THE FULLEST EXTENT POSSIBLE BY LAW, IN NO EVENT SHALL ASIE, ITS SUBSDIARIES, OR ANY THIRD PARTIES MENTIONED ON ANY ASIE SITE BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL AND CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA, LOST EMPLOYMENT OPPORTUNITY OR BUSINESS INTERRUPTION) RESULTING FROM THE USE OR INABILITY TO USE ANY ASIE SITE AND ITS CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ASIE IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
					<b>16. Links to Other Sites:</b>
					<hr/>
					<p>The ASIE Sites may contain links to third party Web sites. These links are provided solely as a convenience to You and not as an endorsement by ASIE of the contents on such third-party Web sites. ASIE is not responsible for the content of linked third-party sites and does not make any representations regarding the content or accuracy of materials on such third-party Web sites. If You decide to access linked third-party Web sites, You do so at Your own risk or will.</p>
					<b>17. No Resale or Unauthorized Commercial Use:</b>
					<hr/>
					<p>You agree not to resell or assign Your rights or obligations under these Terms. You also agree not to make any unauthorized commercial use of any ASIE Site.</p>
					<b>18. Indemnity:</b>
					<hr/>
					<p>You the Users agree to defend, indemnify, and hold harmless ASIE/AJM, its affiliates, collaborators and their respective officers, directors, employees and agents, from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from (i) any User Content or other material You provide to any ASIE Site, (ii) Your use of any ASIE Content, or (iii) Your breach of these Terms. ASIE shall provide notice to You promptly of any such claim, suit, or proceeding.</p>
					<b>19. Mobile Services:</b>
					<hr/>
					<p>If You use the ASIE Sites through a mobile device, You agree that information about Your use of the ASIE Sites through Your mobile device and carrier may be communicated to us, including but not limited to Your mobile carrier, Your mobile device, or Your physical location. In addition, use of the ASIE Sites through a mobile device may also cause data to be displayed on and through Your mobile device. By accessing the ASIE Sites using a mobile device, You represent that to the extent You import any of Your ASIE data to Your mobile device that You have authority to share the transferred data with Your mobile carrier or other access provider. In the event You change or deactivate Your mobile account, You must promptly update Your ASIE account information to ensure that Your messages are not sent to the person that acquires Your old number and failure to do so is Your responsibility. You acknowledge You are responsible for all charges and necessary permissions related to accessing the ASIE Sites through Your mobile access provider. Therefore, You should check with Your provider to find out if the ASIE Sites are available and the terms for these services for Your specific mobile devices.</p>
					<b>24. General Condition:</b>
					<hr/>
					<p>ASIE makes no claims or representations that the ASIE Content may be lawfully viewed or accessed outside of the United States. Access to the ASIE Content may not be legal by certain persons or in certain countries. If You access any ASIE Site You do so at Your own risk and are responsible for compliance with the laws of Your jurisdiction. Any software downloaded from any ASIE Site is further subject to United States export control laws, and may not be downloaded or otherwise exported or re-exported (i) into (or to a national or resident of) Cuba, Iraq, Libya, North Korea, Iran, Syria or any other country to which the U.S. has embargoed goods or (ii) to any individual or entity on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Commerce Department’s Table of Deny Orders. By downloading or using such software, You represent and warrant that You are not located in, under the control of, or a national or resident of any such country, individual, or entity on any such list. </p>
					<p>These Terms are governed by the internal substantive laws of the State of California, without respect to its conflict of laws principles. Jurisdiction for any claims arising under this agreement shall lie exclusively with the state or federal courts within California. If any provision of these Terms are found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms, which shall remain in full force and effect. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term. In addition, ASIE’s failure to enforce any term of these Terms shall not be deemed as a waiver of such term or otherwise affect ASIE’s ability to enforce such term at any point in the future. Except as expressly provided in an additional agreement, additional Terms for certain areas of the ASIE Sites, a particular "Legal Notice," or software license or material on particular pages on the ASIE Sites, these Terms constitute the entire agreement between You and ASIE with respect to the use of the ASIE/AJM Sites. No changes to these Terms shall be made except by a revised posting on this page. </p>
					<b><i>By using any downloadable application to enable Your use of the ASIE/AJM Sites, You are explicitly confirming Your acceptance of the ABOVE terms of the End User License Agreement associated with the Application provided at download or installation, or as THE CASE may be updated from time to time.</i></b>
					<br/><br/>
					<p>Last updated on April 13, 2018</p>
				</div>
			</div>
		);
	}
}